function drawConfiguration( q , radius , box , colors , edgeColors )
    for i = 1 : length(radius) ,
        rectangle( ...
            'Position',[q(2*i-1)-radius(i) q(2*i)-radius(i) ...
            2*radius(i) 2*radius(i)], ...
            'Curvature',[1 1], 'FaceColor',colors(i,:)